version: "3.8"

services: 
  app:
    build: ./application
    container_name: simple_application
    # ports:
    #   - "8080:80"
    expose:
      - "80"

    volumes:
      ## Just for development
      # - ./application/src:/var/www/html
      ## Mount logs to the host machine for easier debugging
      - ./logs/apache:/var/log/apache2
      - ./logs/php:/var/log
      - ./application/apache.conf:/etc/apache2/conf-available/security.conf:ro

    ## Run MySQL service first and then run app service --> ensure the connection
    depends_on:
      - mysql
    environment:
      - DB_HOST
      - DB_NAME
      - DB_USER
      - DB_PWD
    networks:
      default:
        ipv4_address: 10.10.0.20

  mysql:
    image: mysql:8.4.5
    container_name: simple_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password

    ## Should not be exposed to the host machine in production (remove the ports line)
    # ports: 
    #   - "3306:3306" 
    expose:
      - "3306"
    volumes:
      - data:/var/lib/mysql  # Save data in a named volume
      - ./logs/mysql:/var/log/mysql # Save logs
      - ./application/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro\
      - ./application/db/my.conf:/etc/mysql/my.cnf:ro
    networks:
      default:
        ipv4_address: 10.10.0.10

  nginx:
    build: ./nginx
    container_name: reverse_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - app
    restart: always
    # read_only: true
    tmpfs:
      - /tmp
    networks:
      default:
        ipv4_address: 10.10.0.30

volumes:
  data: # /var/lib/docker/volumes/<project name>_data/_data/


# Confiure the network to use statis IPs
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16