version: "3.8"

services: 
  app:
    build: ./application
    container_name: simple_application
    ports:
      - "8080:80"
      
    ## Just for development
    # volumes:
    #   - ./application/src:/var/www/html